version: 2.1

orbs:
  architect: giantswarm/architect@4.26.0

workflows:
  version: 2
  build:
    jobs:
      - architect/go-build:
          name: build-aws-ebs-csi-volume-limiter
          context: architect
          binary: aws-ebs-csi-volume-limiter
          filters:
            # Do this on every commit and when a new tag is created.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-aws-ebs-csi-volume-limiter
          context: architect
          image: "quay.io/giantswarm/aws-ebs-csi-volume-limiter"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build-aws-ebs-csi-volume-limiter
          # Do this on every commit and when a new tag is created.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-aws-ebs-csi-volume-limiter-to-aliyun
          context: architect
          image: "giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/aws-ebs-csi-volume-limiter"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build-aws-ebs-csi-volume-limiter
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
